// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExampleService.proto

package com.cerner.viewer.demo.java.grpc;

public final class ExampleService {
  private ExampleService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cerner_viewer_demo_java_grpc_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cerner_viewer_demo_java_grpc_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cerner_viewer_demo_java_grpc_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cerner_viewer_demo_java_grpc_HelloResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cerner_viewer_demo_java_grpc_HelloResponse_BagsOfTricksEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cerner_viewer_demo_java_grpc_HelloResponse_BagsOfTricksEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ExampleService.proto\022 com.cerner.viewe" +
      "r.demo.java.grpc\"\034\n\014HelloRequest\022\014\n\004name" +
      "\030\001 \001(\t\"\300\001\n\rHelloResponse\022\020\n\010greeting\030\001 \001" +
      "(\t\022\017\n\007hobbies\030\002 \003(\t\022W\n\014bagsOfTricks\030\003 \003(" +
      "\0132A.com.cerner.viewer.demo.java.grpc.Hel" +
      "loResponse.BagsOfTricksEntry\0323\n\021BagsOfTr" +
      "icksEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028" +
      "\0012~\n\017GreetingService\022k\n\010greeting\022..com.c" +
      "erner.viewer.demo.java.grpc.HelloRequest" +
      "\032/.com.cerner.viewer.demo.java.grpc.Hell" +
      "oResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_cerner_viewer_demo_java_grpc_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_cerner_viewer_demo_java_grpc_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cerner_viewer_demo_java_grpc_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_cerner_viewer_demo_java_grpc_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_cerner_viewer_demo_java_grpc_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cerner_viewer_demo_java_grpc_HelloResponse_descriptor,
        new java.lang.String[] { "Greeting", "Hobbies", "BagsOfTricks", });
    internal_static_com_cerner_viewer_demo_java_grpc_HelloResponse_BagsOfTricksEntry_descriptor =
      internal_static_com_cerner_viewer_demo_java_grpc_HelloResponse_descriptor.getNestedTypes().get(0);
    internal_static_com_cerner_viewer_demo_java_grpc_HelloResponse_BagsOfTricksEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cerner_viewer_demo_java_grpc_HelloResponse_BagsOfTricksEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
