// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExampleService.proto

package com.cerner.viewer.demo.java.grpc;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cerner.viewer.demo.java.grpc.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greeting = 1;</code>
   */
  java.lang.String getGreeting();
  /**
   * <code>string greeting = 1;</code>
   */
  com.google.protobuf.ByteString
      getGreetingBytes();

  /**
   * <code>repeated string hobbies = 2;</code>
   */
  java.util.List<java.lang.String>
      getHobbiesList();
  /**
   * <code>repeated string hobbies = 2;</code>
   */
  int getHobbiesCount();
  /**
   * <code>repeated string hobbies = 2;</code>
   */
  java.lang.String getHobbies(int index);
  /**
   * <code>repeated string hobbies = 2;</code>
   */
  com.google.protobuf.ByteString
      getHobbiesBytes(int index);

  /**
   * <code>map&lt;string, string&gt; bagsOfTricks = 3;</code>
   */
  int getBagsOfTricksCount();
  /**
   * <code>map&lt;string, string&gt; bagsOfTricks = 3;</code>
   */
  boolean containsBagsOfTricks(
      java.lang.String key);
  /**
   * Use {@link #getBagsOfTricksMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getBagsOfTricks();
  /**
   * <code>map&lt;string, string&gt; bagsOfTricks = 3;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getBagsOfTricksMap();
  /**
   * <code>map&lt;string, string&gt; bagsOfTricks = 3;</code>
   */

  java.lang.String getBagsOfTricksOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; bagsOfTricks = 3;</code>
   */

  java.lang.String getBagsOfTricksOrThrow(
      java.lang.String key);
}
